---
- name: Add Aliases
  template:
    src: ../config/aliases.sh.j2
    dest: /etc/profile.d/my-aliases.sh

- name: Add PS1
  template:
    src: ../config/ps1.sh.j2
    dest: /etc/profile.d/my-ps1.sh
