---
- name: Add Aliases
  ansible.builtin.copy:
    src: ../config/aliases.sh
    dest: /etc/profile.d/my-aliases.sh

- name: Add PS1
  ansible.builtin.template:
    src: ../config/ps1.sh.j2
    dest: /etc/profile.d/my-ps1.sh
