---
- name: Install PHP Packages
  ansible.builtin.apt:
    name: ['php7.2', 'php7.2-fpm', 'php7.2-cli', 'php7.2-curl', 'php7.2-mysql', 'php7.2-curl', 'php7.2-gd', 'php7.2-mbstring', 'php-pear']
    state: present

- name: Start and Enable php7.2-fpm
  ansible.builtin.systemd:
    name: php7.2-fpm
    state: started
    enabled: true
