---
- hosts: "{{ name }}"
  remote_user: ubuntu
  become: true
  collections:
    - devsec.hardening
  roles:
    - ssh_hardening

  vars:
    name: lab

  tasks:
    - name: Set hostname to server
      include_role:
        name: host-management
      vars:
        hosts_additional_hosts:
          - address: 127.0.0.1
            hostnames:
              - "{{ name }}.gg.test"

    - include: plays/profile.yml
